ngadmin_layouts_location_layouts:
    path: /ngadmin/layouts/{locationId}
    defaults:
        _controller: "netgen_admin_ui.controller.layouts:showLocationLayouts"
    methods:  [GET]

ngadmin_layouts_layout_wizard:
    path: /ngadmin/layouts/{locationId}/wizard
    controller: netgen_admin_ui.controller.layout_wizard
    methods:  [GET, POST]
    
ngadmin_layouts_layout_wizard_callback:
    path: /ngadmin/layouts/{locationId}/wizard/callback
    controller: netgen_admin_ui.controller.layout_wizard_callback
    methods:  [GET]

ngadmin_layouts_rules_delete_rule:
    path: /ngadmin/layouts/rules/{ruleId}/delete
    controller: netgen_admin_ui.controller.delete_rule
    methods:  [DELETE]
    defaults:
        _nglayouts_status: published

_ezpublishPreviewContentDefaultSa:
    path: /content/versionview/{contentId}/{versionNo}/{language}
    defaults:
        _controller: "ezpublish_legacy.controller:indexAction"
    methods:  [GET]

_ezpublishSearchRoute:
    path: /content/search
    defaults:
        _controller: "ezpublish_legacy.controller:indexAction"

# Overrides for eZ Platform Admin UI routes conflicting with eZ Publish Legacy
# https://github.com/ezsystems/ezplatform-admin-ui/pull/287

ezplatform.section.list:
    path: /sections/list
    defaults:
        _controller: 'EzSystems\EzPlatformAdminUiBundle\Controller\SectionController::listAction'

ezplatform.section.view:
    path: /sections/view/{sectionId}
    defaults:
        _controller: 'EzSystems\EzPlatformAdminUiBundle\Controller\SectionController::viewAction'

ezplatform.role.list:
    path: /roles/list
    methods: ['GET']
    defaults:
        _controller: 'EzSystems\EzPlatformAdminUiBundle\Controller\RoleController::listAction'

ezplatform.object_state.groups.list:
    path: /state/groups/list
    defaults:
        _controller: 'EzSystems\EzPlatformAdminUiBundle\Controller\ObjectStateGroupController::listAction'

ezplatform.object_state.group.view:
    path: /state/groups/{objectStateGroupId}
    defaults:
        _controller: 'EzSystems\EzPlatformAdminUiBundle\Controller\ObjectStateGroupController::viewAction'

ezplatform.object_state.group.add:
    path: /state/groups/create
    defaults:
        _controller: 'EzSystems\EzPlatformAdminUiBundle\Controller\ObjectStateGroupController::addAction'
